### ISSUE TITLE
runRefineSecondaryTiming.py options

### ISSUE THREAD

**Issue by 10golo** [isce-framework/isce2#522] opened 2022-07-07 17:42 UTC
Hello,

I have the following warning in the misregistration step:
```
step=misregistration
WARNING - number of samples availabe for estating gross offset is NOT power of 2:          80
           the value is computed as 2*i_srchy/winsize_filt
           better to make it power of 2 for FFT
           current i_srchy (azimuth search window size):          40
           current winsize_filt (azimuth filtering window size):           1
CAUTION - Requesting very large search window pull in
Reference Window Size is                     128 sample pixels
Number of Search Pixels is                    40 sample pixels
The rule of thumb is that the search window pull in is at least 5
pixels and is less than the reference window size divided by 5.
Suggested Number of Search Pixels is          21 sample pixels


CAUTION - Requesting very large search window pull in
Reference Window Size is                     128 line pixels
Number of Search Pixels is                    40 line pixels
The rule of thumb is that the search window pull in is at least 5
pixels and is less than the reference window size divided by 5.
Suggested Number of Search Pixels is          21 line pixels


Requested resolving shifts to 1/   32 of a pixel

INFORMATION - you choose skips which are small for your window sizes
Normally the skip size is bigger than the box size
Across your skip is        186 but your window is        128
Down   your skip is        103 but your window is        128
This means that the image chips are larger than the separation between chips
```

I looked at the options to switch and these are (if I'm correct):
```
    objOffset.setWindowSizeWidth(128)
    objOffset.setWindowSizeHeight(128)
    objOffset.setSearchWindowSizeWidth(40)
    objOffset.setSearchWindowSizeHeight(40)
```
Is there any way to switch these options from the XML file and not directly on the runRefineSecondaryTiming.py file?

Thanks!

**Comment by EJFielding** [comment] 2022-07-10 01:00
You can disregard the warnings. The `runRefineSecondaryTiming.py` file is calling the ISCE2 function `ampCor` and the `ampCor` routine gives these informational warnings but the calculations are still correct.

**Comment by rtburns-jpl** [comment] 2022-11-01 23:41
Sounds like this is working as intended then, closing

**Closed by rtburns-jpl** 2022-11-01 23:41 UTC
