### ISSUE TITLE
DEM.py issues with Python 3.10

### ISSUE THREAD

**Issue by ZachKeskinen** [isce-framework/isce2#506] opened 2022-06-19 21:52 UTC
I was calling dem.py to install a DEM and correct it to WGS84. However, I got the error:

SystemError: PY_SSIZE_T_CLEAN macro must be defined for '#' formats

It looked like it might be a python 3.10 issue based on [this](https://stackoverflow.com/questions/70705404/systemerror-py-ssize-t-clean-macro-must-be-defined-for-formats). After I downgraded my environment's python to 3.9.0 I did not get the error running the same command.

**Comment by rtburns-jpl** [comment] 2022-11-01 21:43
Closing as duplicate of #458

**Closed by rtburns-jpl** 2022-11-01 21:43 UTC
Labels: bug, duplicate
